[HDFS_Namenode] fix break
In https://github.com/DataDog/integrations-core/pull/1107 a bug was introduced so that if no `tags` are specified on an instance, the check crashes:

```
hdfs_namenode (5.22.0)
----------------------
  - instance #0 [ERROR]: "'NoneType' object has no attribute 'append'"
    Traceback (most recent call last):
      File "/opt/datadog-agent/agent/checks/__init__.py", line 812, in run
        self.check(copy.deepcopy(instance))
      File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/hdfs_namenode/hdfs_namenode.py", line 99, in check
        tags.append('namenode_url:' + jmx_address)
    AttributeError: 'NoneType' object has no attribute 'append'
```

Temporary workaround for those that don't use tags is to simply set `tags: []` in your instance settings.