Fix possible TypeError due to NoneType in parser.isoparse (#5265)
* Fixes TypeError returned by iparser.isoparse

TypeError: object of type 'NoneType' has no len() returned by parser.isoparse if data does not contain an expiration_date due to null response or err in response.

* Raise an exception if Twistlock returns err in response

e.g. { "err": "invalid credentials" }

* Add test - err in response

* style fix