add missing arguments to log statement (#12499)
If the postgres user the agent is connecting with isn't allowed to read
all queries in pg_stat_activity, a warning is logged. But the log
message can't be formatted due to missing arguments, resulting in:

pkg/collector/python/datadog_agent.go:122 in LogMessage) [...] Job loop crash
Traceback (most recent call last):
[...]
TypeError: not enough arguments for format string