Fixes TypeError if/when services are culled
The data type of 'services' returned by the function _cull_services_list if/when services are culled becomes a <list> from a <dict>. 

Below error will then be encountered when the function _get_service_tags(service, services[service]) is called with "services" being of type <list>

TypeError: list indices must be integers, not unicode