Revert "Fix (attempt)"
This reverts commit e9af7268732137a99a639c62d4192a922dba147e.

This rewrite was useless since it was still generating the following error:

```
style run-test: commands[3] | mypy --config-file=../mypy.ini --py2 --check-untyped-defs --follow-imports silent datadog_checks/base/checks/base.py datadog_checks/base/checks/win/wmi/__init__.py datadog_checks/base/checks/win/winpdh_base.py
datadog_checks/base/checks/base.py:212:13: error: Attribute "hostname" already defined on line 210
Found 1 error in 1 file (checked 3 source files)
ERROR: InvocationError for command /home/vsts/work/1/s/datadog_checks_base/.tox/style/bin/mypy --config-file=../mypy.ini --py2 --check-untyped-defs --follow-imports silent datadog_checks/base/checks/base.py datadog_checks/base/checks/win/wmi/__init__.py datadog_checks/base/checks/win/winpdh_base.py (exited with code 1)
```