add test to force probe of all ports/configs to check no side effects on server
To ensure that this no risk with probing the ports of the container for
configuration discovery, add a test which instanciates the integration which
each of the generated configurations in turn and checks that the container logs
don't have any obvious crashes.

 https://datadoghq.atlassian.net/wiki/spaces/DSCVR/pages/6671862234/Configuration+Discovery+for+Agent+Integrations#Probing-causes-problems

While the logic for detecting "bad" effects is best-effort, the test also the
logs from this scenario to be seen easier during development.

For example, for krakend:

```
$ ddev env test --base --new-env krakend py3.13-2.10 -- -k test_e2e_discovery_candidates_do_not_destabilize_container -rP --log-level=DEBUG
...
_________ test_e2e_discovery_candidates_do_not_destabilize_container __________
------------------------------ Captured log call -------------------------------
DEBUG    root:docker.py:90 Probing candidate #1: {'init_config': {}, 'instances': [{'openmetrics_endpoint': 'http://172.17.129.3:9090/metrics'}]}
DEBUG    root:docker.py:90 Probing candidate #2: {'init_config': {}, 'instances': [{'openmetrics_endpoint': 'http://172.17.129.3:8080/metrics'}]}
DEBUG    root:docker.py:94 Error probing candidate #2: {'init_config': {}, 'instances': [{'openmetrics_endpoint': 'http://172.17.129.3:8080/metrics'}]}
DEBUG    root:docker.py:103 New log line: [GIN] 2026/06/17 - 15:31:46 | 404 |       2.803µs |    172.17.129.1 | GET      "/metrics"
DEBUG    root:docker.py:103 New log line: [GIN] 2026/06/17 - 15:31:47 | 404 |       2.753µs |    172.17.129.1 | GET      "/metrics"
DEBUG    root:docker.py:90 Probing candidate #3: {'init_config': {}, 'instances': [{'openmetrics_endpoint': 'http://172.17.129.3:8090/metrics'}]}
DEBUG    root:docker.py:94 Error probing candidate #3: {'init_config': {}, 'instances': [{'openmetrics_endpoint': 'http://172.17.129.3:8090/metrics'}]}
DEBUG    root:docker.py:103 New log line: [GIN] 2026/06/17 - 15:31:49 | 200 |      51.868µs |             ::1 | GET      "/__health"
```