postgres check: bump datadog_checks_base min version
Fix broken build due to old datadog_checks_base minimum version.

```
E   ImportError: cannot import name 'compute_exec_plan_signature' from 'datadog_checks.base.utils.db.sql' (/home/vsts/work/1/s/postgres/.tox/py38/lib/python3.8/site-packages/datadog_checks/base/utils/db/sql.py)
```

Follow-up to https://github.com/DataDog/integrations-core/pull/8627

Depends on https://github.com/DataDog/integrations-core/pull/8759