redisdb: catch NoPermissionError instead of crashing if client metrics can't be collected
We encountered these traces when trying to collect client metrics with a bad configuration:

```
2021-04-20 16:21:10 UTC | CORE | ERROR | (pkg/collector/runner/runner.go:292 in work) | Error running check redisdb: [{"message": "this user has no permissions to run the 'client' command or its subcommand", "traceback": "Traceback (most recent call last):
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py\", line 897, in run
    self.check(instance)
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/redisdb/redisdb.py\", line 500, in check
    self._check_db()
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/redisdb/redisdb.py\", line 260, in _check_db
    clients = conn.client_list()
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/client.py\", line 1194, in client_list
    return self.execute_command('CLIENT LIST')
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/client.py\", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/client.py\", line 915, in parse_response
    response = connection.read_response()
  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py\", line 756, in read_response
    raise response
redis.exceptions.NoPermissionError: this user has no permissions to run the 'client' command or its subcommand
"}]
```

Most of the metrics worked but the ones following this check were skipped (`redis.net.commands` and `redis.net.instantaneous_ops_per_sec`)

Catch the error, log it but continue collecting metrics