Add Linux support tag to manifest (#22955)
[7.78.x]
When releasing new integrations with `ddev release make all --new`:
```
ManifestError: Can't parse the supported OS list for the check beyondtrust_privileged_remote_access: []
```

(cherry picked from commit 0509aa0ad250e7342816758843454d38d17eb5e6)