Fixes TypeError returned by iparser.isoparse
TypeError: object of type 'NoneType' has no len() returned by parser.isoparse if data does not contain an expiration_date due to null response or err in response.