Add minimal e2e test to exchange_server (#12110)
* Add minimal e2e test to exchange_server

* Solved 'E302 expected 2 blank lines, found 1' error

* Solved format style error

* Added conftest.py

* Added INSTANCE to common.py to solve 'ImportError: cannot import name INSTANCE'

* Added needed fixtures

* Changed service check to windows perf health

* e2e tests only in py38

* e2e tests moved to an independent file

* e2e test result changed to OK

* Removed unused fixture

* Added assertion about no metrics being emitted

* Commented call to configure_perf_objects

* Commented most of _query_counters

* Uncommented call to configure_perf_objects

* check only executes 'submit_health_check'

* Restored original check

* Testing with empty metrics in default config

* Restored metrics in default config to original value

* Testing PerfObject

* Corrected call to TestPerfObject

* Removed call to TestPerfObject

* Submit CRITICAL health check value if a perf object collect raises an exception

* Restored base.py

* Check metric names is empty

* Reformatted test_e2e.py file

* Commented metric names check

* Added check for empty metrics

* Removed unseen instances check

* Restored unseen instances check

* Removed some metrics

* Removed some performance objects

* Restored Network Interface performance object and metrics

* Restored Processor performance object and metrics

* Restored all performance object and metrics

* Updated e2e test

* Corrected format in metric_full_name

* Corrected typo

* Corrected format error