Skip non-local keys (#798)
* Skip non-local keys

This will allow the configuration to be the same on several redis hosts, and the key length will only be collected for the keys that are assigned to the monitored host.

Without this change, when the check encounters a key that is MOVED, it responds with the following error and does not report *any* key length information, even if several keys are listed, and some are local:
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 788, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/redisdb.py", line 367, in check
    self._check_db(instance, custom_tags)
  File "/opt/datadog-agent/agent/checks.d/redisdb.py", line 237, in _check_db
    key_type = conn.type(key)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/redis/client.py", line 1129, in type
    return self.execute_command('TYPE', name)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
ResponseError: MOVED 12648 162.222.64.193:6379

* Fixed indentation